server:
  port: 8761
eureka:
  #server:
   #enableSelfPreservation: false
  instance:
    hostname: localhost 
  client:
   registerWithEureka: false
   #register-with-eureka: false
   fetchRegistry: false
   #fetch-registry: false
   serviceUrl: 
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   
 
 